Summary:	Editing Tool for Vnc2swf
Summary(pl.UTF-8):	Narzędzie do edycji dla Vnc2swf
Name:		edit_vnc2swf
Version:	0.3
Release:	1
License:	GPL v2
Group:		Applications/Multimedia
Source0:	http://www.unixuser.org/~euske/vnc2swf/%{name}-%{version}.tar.gz
# Source0-md5:	606ed2294b20f1d2aa198d7d66ce82c3
URL:		http://www.unixuser.org/~euske/vnc2swf/edit_vnc2swf.html
BuildRequires:	sed >= 4.0
Requires:	python >= 1:2.3
Requires:	python-pygame >= 1.6
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Edit_vnc2swf is an editing tool for vnc2swf. This program allows you
to chop, splice, crop, and attach an MP3 audio to a .swf (ShockWave
Flash) movie generated by vnc2swf. Also this program does some
optimization to reduce the movie size a little bit. From version 0.2,
it supports ScreenVideo format which was newly introduced in Flash
version 7. Generally with this new format a movie can lose the weight
without losing the quality, and it requires much less memory to play
on your browser.

%description -l pl.UTF-8
Edit_vnc2swf to narzędzie do edycji dla vnc2swf. Ten program umożliwia
cięcie, łączenie, wycinanie i dołączanie dźwięku MP3 do filmów .swf
(ShockWave Flash) wygenerowanych przez vnc2swf. Ten program wykonuje
także pewną optymalizację w celu zmniejszenia nieco rozmiaru filmu. Od
wersji 0.2 obsługuje format ScreenVideo niedawno wprowadzony w wersji
7 Flasha. Zasadniczo przy użyciu tego nowego formatu film może
zmniejszyć rozmiar bez utraty jakości i wymaga dużo mniej pamięci do
odtwarzania w przeglądarce.

%prep
%setup -q

%{__sed} -i -e '1s,#!/usr/bin/env python,#!/usr/bin/python,' edit_*.py

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT%{_bindir}

install edit_mp3.py $RPM_BUILD_ROOT%{_bindir}
install edit_vnc2swf.py $RPM_BUILD_ROOT%{_bindir}

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc README.html
%attr(755,root,root) %{_bindir}/edit_mp3.py
%attr(755,root,root) %{_bindir}/edit_vnc2swf.py
